export const enum WATERMARK {
  INJECTABLE = "__INJECTABLE__",
  INJECT = "__INJECT__",
  BEFORE_EXECUTE = "__BEFORE_EXECUTE__",
  AFTER_EXECUTE = "__AFTER_EXECUTE__",
  VALUE = "__VALUE__",
  COMPONENT = "__COMPONENT__",
}
