// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/node_modules/.pnpm/@umijs+renderer-react@4.0.88_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from '/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/node_modules/.pnpm/@umijs+renderer-react@4.0.88_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/node_modules/.pnpm/umi@4.0.88_@babel+core@7.23.3_@types+node@20.9.2_eslint@8.54.0_prettier@3.1.0_react-dom@18.2._t3miyk7722yw2qo5yfyklyfsd4/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
export const useServerInsertedHTML: Function = () => {};
// plugins
export { getSketchJSON } from '/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/docs/.dumi/tmp/plugin-html2sketch';
// plugins types.d.ts
