// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide/introduction/start-raw":{"path":"guide/introduction/start-raw","id":"docs/guide/introduction/start-raw","parentId":"DocLayout"},"docs/guide/introduction/index":{"path":"guide/introduction","id":"docs/guide/introduction/index","parentId":"DocLayout"},"docs/guide/core/inject":{"path":"guide/core/inject","id":"docs/guide/core/inject","parentId":"DocLayout"},"docs/guide/index":{"path":"guide","id":"docs/guide/index","parentId":"DocLayout"},"docs/index.en-US":{"path":"en-US/","id":"docs/index.en-US","parentId":"DocLayout"},"docs/api/index":{"path":"api","id":"docs/api/index","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.3_@types+node@20.9.2_eslint@8.54.0_prettier@3.1.0_react-dom@18.2_ub3efl4qlos6enj4swh32rt6bm/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/docs/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.3_@types+node@20.9.2_eslint@8.54.0_prettier@3.1.0_react-dom@18.2_ub3efl4qlos6enj4swh32rt6bm/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide/introduction/start-raw': React.lazy(() => import(/* webpackChunkName: "docs__guide__introduction__start-raw.md" */'/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/docs/docs/guide/introduction/start-raw.md')),
'docs/guide/introduction/index': React.lazy(() => import(/* webpackChunkName: "docs__guide__introduction__index.md" */'/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/docs/docs/guide/introduction/index.md')),
'docs/guide/core/inject': React.lazy(() => import(/* webpackChunkName: "docs__guide__core__inject.md" */'/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/docs/docs/guide/core/inject.md')),
'docs/guide/index': React.lazy(() => import(/* webpackChunkName: "docs__guide__index.md" */'/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/docs/docs/guide/index.md')),
'docs/index.en-US': React.lazy(() => import(/* webpackChunkName: "docs__index.en-US.md" */'/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/docs/docs/index.en-US.md')),
'docs/api/index': React.lazy(() => import(/* webpackChunkName: "docs__api__index.md" */'/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/docs/docs/api/index.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/docs/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.3_@types+node@20.9.2_eslint@8.54.0_prettier@3.1.0_react-dom@18.2_ub3efl4qlos6enj4swh32rt6bm/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
