export const enum NailyWebWatermark {
  CONTROLLER = "__Naily:WEB:CONTROLLER__",
  CONTROLLER_METHOD = "__Naily:WEB:CONTROLLER_METHOD__",
  CONTROLLER_METHOD_PARAMETER = "__Naily:WEB:CONTROLLER_METHOD_PARAMETER__",

  ADVICE = "__Naily:WEB:ADVICE__",
  USEADVICE = "__Naily:WEB:USEADVICE__",
}
