export const enum NailyWebWatermark {
  CONTROLLER = "__CONTROLLER__",
  GET = "__GET__",
  POST = "__POST__",
  PUT = "__PUT__",
  DELETE = "__DELETE__",
  PATCH = "__PATCH__",
  HEAD = "__HEAD__",
  ALL = "__ALL__",
  OPTIONS = "__OPTIONS__",
  TRACE = "__TRACE__",
  REQ = "__REQ__",
  RES = "__RES__",
  NEXT = "__NEXT__",
  HEADERS = "__HEADERS__",
  PARAM = "__PARAM__",
  QUERY = "__QUERY__",
  BODY = "__BODY__",
  IP = "__IP__",
}
