// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/guhuan/Documents/Personal/NailyProjects/naily/v21/node_modules/.pnpm/dumi@2.2.14_@babel+core@7.23.3_@types+node@20.9.2_eslint@8.54.0_prettier@3.1.0_react-dom@18.2_ub3efl4qlos6enj4swh32rt6bm/node_modules/dumi/theme-default/slots/ContentTabs/index.js';
